<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\User' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\User' . "\0" . 'disponible_debut', '' . "\0" . 'App\\Entity\\User' . "\0" . 'disponible_fin', '' . "\0" . 'App\\Entity\\User' . "\0" . 'service', '' . "\0" . 'App\\Entity\\User' . "\0" . 'rdv_prendre', '' . "\0" . 'App\\Entity\\User' . "\0" . 'rdv_gerer', '' . "\0" . 'App\\Entity\\User' . "\0" . 'parti', '' . "\0" . 'App\\Entity\\User' . "\0" . 'urgence_demande', '' . "\0" . 'App\\Entity\\User' . "\0" . 'urgence_gerer'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\User' . "\0" . 'date_naissance', '' . "\0" . 'App\\Entity\\User' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\User' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\User' . "\0" . 'disponible_debut', '' . "\0" . 'App\\Entity\\User' . "\0" . 'disponible_fin', '' . "\0" . 'App\\Entity\\User' . "\0" . 'service', '' . "\0" . 'App\\Entity\\User' . "\0" . 'rdv_prendre', '' . "\0" . 'App\\Entity\\User' . "\0" . 'rdv_gerer', '' . "\0" . 'App\\Entity\\User' . "\0" . 'parti', '' . "\0" . 'App\\Entity\\User' . "\0" . 'urgence_demande', '' . "\0" . 'App\\Entity\\User' . "\0" . 'urgence_gerer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(?\DateTimeInterface $date_naissance): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$date_naissance]);

        return parent::setDateNaissance($date_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(?string $adresse): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(?string $photo): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(int $telephone): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossier', []);

        return parent::getDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDossier(?string $dossier): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDossier', [$dossier]);

        return parent::setDossier($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibleDebut(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibleDebut', []);

        return parent::getDisponibleDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibleDebut(?int $disponible_debut): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibleDebut', [$disponible_debut]);

        return parent::setDisponibleDebut($disponible_debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibleFin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibleFin', []);

        return parent::getDisponibleFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibleFin(?int $disponible_fin): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibleFin', [$disponible_fin]);

        return parent::setDisponibleFin($disponible_fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getService(): ?\App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', []);

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setService(?\App\Entity\Service $service): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', [$service]);

        return parent::setService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getRdvPrendre(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRdvPrendre', []);

        return parent::getRdvPrendre();
    }

    /**
     * {@inheritDoc}
     */
    public function addRdvPrendre(\App\Entity\Rdv $rdvPrendre): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRdvPrendre', [$rdvPrendre]);

        return parent::addRdvPrendre($rdvPrendre);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRdvPrendre(\App\Entity\Rdv $rdvPrendre): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRdvPrendre', [$rdvPrendre]);

        return parent::removeRdvPrendre($rdvPrendre);
    }

    /**
     * {@inheritDoc}
     */
    public function getRdvGerer(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRdvGerer', []);

        return parent::getRdvGerer();
    }

    /**
     * {@inheritDoc}
     */
    public function addRdvGerer(\App\Entity\Rdv $rdvGerer): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRdvGerer', [$rdvGerer]);

        return parent::addRdvGerer($rdvGerer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRdvGerer(\App\Entity\Rdv $rdvGerer): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRdvGerer', [$rdvGerer]);

        return parent::removeRdvGerer($rdvGerer);
    }

    /**
     * {@inheritDoc}
     */
    public function getParti(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParti', []);

        return parent::getParti();
    }

    /**
     * {@inheritDoc}
     */
    public function addParti(\App\Entity\Participant $parti): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParti', [$parti]);

        return parent::addParti($parti);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParti(\App\Entity\Participant $parti): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParti', [$parti]);

        return parent::removeParti($parti);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrgenceDemande(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrgenceDemande', []);

        return parent::getUrgenceDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function addUrgenceDemande(\App\Entity\DemandeUrgence $urgenceDemande): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUrgenceDemande', [$urgenceDemande]);

        return parent::addUrgenceDemande($urgenceDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUrgenceDemande(\App\Entity\DemandeUrgence $urgenceDemande): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUrgenceDemande', [$urgenceDemande]);

        return parent::removeUrgenceDemande($urgenceDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrgenceGerer(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrgenceGerer', []);

        return parent::getUrgenceGerer();
    }

    /**
     * {@inheritDoc}
     */
    public function addUrgenceGerer(\App\Entity\DemandeUrgence $urgenceGerer): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUrgenceGerer', [$urgenceGerer]);

        return parent::addUrgenceGerer($urgenceGerer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUrgenceGerer(\App\Entity\DemandeUrgence $urgenceGerer): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUrgenceGerer', [$urgenceGerer]);

        return parent::removeUrgenceGerer($urgenceGerer);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
