<?php

namespace ContainerF6GOrpQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WpbWpEXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WpbWpEX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WpbWpEX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminEventController::delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\AdminEventController::edit' => ['privates', '.service_locator.VBenu7k', 'get_ServiceLocator_VBenu7kService', true],
            'App\\Controller\\AdminEventController::index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\AdminEventController::new' => ['privates', '.service_locator.UYKJCNY', 'get_ServiceLocator_UYKJCNYService', true],
            'App\\Controller\\AdminEventController::show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminEventController:delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\AdminEventController:edit' => ['privates', '.service_locator.VBenu7k', 'get_ServiceLocator_VBenu7kService', true],
            'App\\Controller\\AdminEventController:index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\AdminEventController:new' => ['privates', '.service_locator.UYKJCNY', 'get_ServiceLocator_UYKJCNYService', true],
            'App\\Controller\\AdminEventController:show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminEventController::delete' => '?',
            'App\\Controller\\AdminEventController::edit' => '?',
            'App\\Controller\\AdminEventController::index' => '?',
            'App\\Controller\\AdminEventController::new' => '?',
            'App\\Controller\\AdminEventController::show' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminEventController:delete' => '?',
            'App\\Controller\\AdminEventController:edit' => '?',
            'App\\Controller\\AdminEventController:index' => '?',
            'App\\Controller\\AdminEventController:new' => '?',
            'App\\Controller\\AdminEventController:show' => '?',
            'App\\Controller\\EventController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
