<?php

namespace Container9KVcFrY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_US8JKR0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.US8JKR0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.US8JKR0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminEventController::delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\AdminEventController::edit' => ['privates', '.service_locator.VBenu7k', 'get_ServiceLocator_VBenu7kService', true],
            'App\\Controller\\AdminEventController::index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\AdminEventController::new' => ['privates', '.service_locator.UYKJCNY', 'get_ServiceLocator_UYKJCNYService', true],
            'App\\Controller\\AdminEventController::show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\AdminParticipantController::delete' => ['privates', '.service_locator.YUeQD7G', 'get_ServiceLocator_YUeQD7GService', true],
            'App\\Controller\\AdminParticipantController::edit' => ['privates', '.service_locator.YUeQD7G', 'get_ServiceLocator_YUeQD7GService', true],
            'App\\Controller\\AdminParticipantController::index' => ['privates', '.service_locator..YVGZja', 'get_ServiceLocator__YVGZjaService', true],
            'App\\Controller\\AdminParticipantController::new' => ['privates', '.service_locator..YVGZja', 'get_ServiceLocator__YVGZjaService', true],
            'App\\Controller\\AdminParticipantController::show' => ['privates', '.service_locator.Ui214X2', 'get_ServiceLocator_Ui214X2Service', true],
            'App\\Controller\\EventController::index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminEventController:delete' => ['privates', '.service_locator.fFHahJ8', 'get_ServiceLocator_FFHahJ8Service', true],
            'App\\Controller\\AdminEventController:edit' => ['privates', '.service_locator.VBenu7k', 'get_ServiceLocator_VBenu7kService', true],
            'App\\Controller\\AdminEventController:index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'App\\Controller\\AdminEventController:new' => ['privates', '.service_locator.UYKJCNY', 'get_ServiceLocator_UYKJCNYService', true],
            'App\\Controller\\AdminEventController:show' => ['privates', '.service_locator.wLYTQQR', 'get_ServiceLocator_WLYTQQRService', true],
            'App\\Controller\\AdminParticipantController:delete' => ['privates', '.service_locator.YUeQD7G', 'get_ServiceLocator_YUeQD7GService', true],
            'App\\Controller\\AdminParticipantController:edit' => ['privates', '.service_locator.YUeQD7G', 'get_ServiceLocator_YUeQD7GService', true],
            'App\\Controller\\AdminParticipantController:index' => ['privates', '.service_locator..YVGZja', 'get_ServiceLocator__YVGZjaService', true],
            'App\\Controller\\AdminParticipantController:new' => ['privates', '.service_locator..YVGZja', 'get_ServiceLocator__YVGZjaService', true],
            'App\\Controller\\AdminParticipantController:show' => ['privates', '.service_locator.Ui214X2', 'get_ServiceLocator_Ui214X2Service', true],
            'App\\Controller\\EventController:index' => ['privates', '.service_locator.Qim_sWz', 'get_ServiceLocator_QimSWzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminEventController::delete' => '?',
            'App\\Controller\\AdminEventController::edit' => '?',
            'App\\Controller\\AdminEventController::index' => '?',
            'App\\Controller\\AdminEventController::new' => '?',
            'App\\Controller\\AdminEventController::show' => '?',
            'App\\Controller\\AdminParticipantController::delete' => '?',
            'App\\Controller\\AdminParticipantController::edit' => '?',
            'App\\Controller\\AdminParticipantController::index' => '?',
            'App\\Controller\\AdminParticipantController::new' => '?',
            'App\\Controller\\AdminParticipantController::show' => '?',
            'App\\Controller\\EventController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminEventController:delete' => '?',
            'App\\Controller\\AdminEventController:edit' => '?',
            'App\\Controller\\AdminEventController:index' => '?',
            'App\\Controller\\AdminEventController:new' => '?',
            'App\\Controller\\AdminEventController:show' => '?',
            'App\\Controller\\AdminParticipantController:delete' => '?',
            'App\\Controller\\AdminParticipantController:edit' => '?',
            'App\\Controller\\AdminParticipantController:index' => '?',
            'App\\Controller\\AdminParticipantController:new' => '?',
            'App\\Controller\\AdminParticipantController:show' => '?',
            'App\\Controller\\EventController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
