<?php

namespace Container9KVcFrY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUeQD7GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YUeQD7G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YUeQD7G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participant' => ['privates', '.errored..service_locator.YUeQD7G.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.YUeQD7G": it references class "App\\Entity\\Participant" but no such service exists.'],
            'participantRepository' => ['privates', 'App\\Repository\\ParticipantRepository', 'getParticipantRepositoryService', true],
        ], [
            'participant' => 'App\\Entity\\Participant',
            'participantRepository' => 'App\\Repository\\ParticipantRepository',
        ]);
    }
}
